[build]
  base = "frontend"

  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/*"
to = "https://react-mesto-ihrf.onrender.com/:splat"
status = 200